### ISSUE TITLE
Clicking "Generate New Random Accounts" more than once causes console error

### ISSUE THREAD

**Issue by Techno11** [FIRST-Tech-Challenge/scorekeeper#106]
When you click the "Generate New Random Accounts" on the 
`event/<EVENTID>/dashboard/defaultaccounts/`
page causes a console error complaining about database errors:
Nothing the end user should ever need to worry about, just figure if you guys were looking for bugs.
Here is an example of one of the errors
```
[qtp1894342191-19] ERROR org.usfirst.ftc.server.SQLiteServerDAO - Error adding user 1819-fim-grayt_referee1 (null)
java.sql.SQLException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (column username is not unique)
        at org.sqlite.DB.newSQLException(DB.java:383)
        at org.sqlite.DB.newSQLException(DB.java:387)
        at org.sqlite.DB.execute(DB.java:342)
        at org.sqlite.DB.executeUpdate(DB.java:363)
        at org.sqlite.PrepStmt.executeUpdate(PrepStmt.java:85)
        at org.usfirst.ftc.server.SQLiteServerDAO.addUser(SQLiteServerDAO.java:191)
        at org.usfirst.ftc.event.management.ManagementSubsystem.createDefaultAccounts(ManagementSubsystem.java:237)
        at org.usfirst.ftc.event.management.ManagementRoutesLogic.lambda$static$3(ManagementRoutesLogic.java:139)
        at spark.RouteImpl$1.handle(RouteImpl.java:72)
        at spark.http.matching.Routes.execute(Routes.java:61)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:130)
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
```

Easy fix, just check if the row already exists, if it does, then execute an UPDATE query instead of an INSERT

**Comment by adwiii** [comment]
This is not a bug - it is telling you that it did not create the account again because it already existed, which functionally is what you want. I *could* change it so that it does not print, but this was what I intended when I wrote this.

**Comment by adwiii** [comment]
The system now logs these to the file, hidden from the user.
