### ISSUE TITLE
The new release doesn't run on macOS

### ISSUE THREAD

**Issue by ofekashery** [FIRST-Tech-Challenge/scorekeeper#183]
**macOS Mojave 10.14**

Log file:
```
[main] INFO org.usfirst.ftc.server.SQLiteServerDAO - Creating server.db
[main] ERROR org.usfirst.ftc.server.SQLiteServerDAO - Error Initializing server.db
java.sql.SQLException: out of memory
	at org.sqlite.DB.throwex(DB.java:370)
	at org.sqlite.NestedDB._open(NestedDB.java:74)
	at org.sqlite.DB.open(DB.java:86)
	at org.sqlite.Conn.open(Conn.java:140)
	at org.sqlite.Conn.<init>(Conn.java:57)
	at org.sqlite.JDBC.createConnection(JDBC.java:77)
	at org.sqlite.JDBC.connect(JDBC.java:64)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at org.usfirst.ftc.server.SQLiteServerDAO.getConnection(SQLiteServerDAO.java:103)
	at org.usfirst.ftc.server.SQLiteServerDAO.init(SQLiteServerDAO.java:114)
	at org.usfirst.ftc.server.SQLiteServerDAO.getInstance(SQLiteServerDAO.java:262)
	at org.usfirst.ftc.server.ServerSubsystem.<init>(ServerSubsystem.java:35)
	at org.usfirst.ftc.server.Server.<clinit>(Server.java:123)
[main] INFO org.usfirst.ftc.server.Server - External Static Files
[main] INFO spark.staticfiles.StaticFilesConfiguration - External StaticResourceHandler configured with folder = ../lib/public
[main] WARN spark.staticfiles.StaticFilesFolder - Registering external static files folder [../lib/public] as [/Users/Desktop/FIRST-Tech-Challenge-Live-0.5.2/bin/../lib/public].
[main] ERROR org.usfirst.ftc.global.SQLiteGlobalDAO - Error loading master team list. 
java.sql.SQLException: out of memory
	at org.sqlite.DB.throwex(DB.java:370)
	at org.sqlite.NestedDB._open(NestedDB.java:74)
	at org.sqlite.DB.open(DB.java:86)
	at org.sqlite.Conn.open(Conn.java:140)
	at org.sqlite.Conn.<init>(Conn.java:57)
	at org.sqlite.JDBC.createConnection(JDBC.java:77)
	at org.sqlite.JDBC.connect(JDBC.java:64)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at org.usfirst.ftc.global.SQLiteGlobalDAO.getConnection(SQLiteGlobalDAO.java:87)
	at org.usfirst.ftc.global.SQLiteGlobalDAO.getMasterTeamList(SQLiteGlobalDAO.java:207)
	at org.usfirst.ftc.global.SQLiteGlobalDAO.init(SQLiteGlobalDAO.java:143)
	at org.usfirst.ftc.server.Server.main(Server.java:245)
java.lang.NullPointerException
	at org.usfirst.ftc.global.SQLiteGlobalDAO.init(SQLiteGlobalDAO.java:143)
	at org.usfirst.ftc.server.Server.main(Server.java:245)
[main] ERROR org.usfirst.ftc.global.SQLiteGlobalDAO - Error loading master team list. 
java.sql.SQLException: out of memory
	at org.sqlite.DB.throwex(DB.java:370)
	at org.sqlite.NestedDB._open(NestedDB.java:74)
	at org.sqlite.DB.open(DB.java:86)
	at org.sqlite.Conn.open(Conn.java:140)
	at org.sqlite.Conn.<init>(Conn.java:57)
	at org.sqlite.JDBC.createConnection(JDBC.java:77)
	at org.sqlite.JDBC.connect(JDBC.java:64)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at org.usfirst.ftc.global.SQLiteGlobalDAO.getConnection(SQLiteGlobalDAO.java:87)
	at org.usfirst.ftc.global.SQLiteGlobalDAO.getMasterTeamList(SQLiteGlobalDAO.java:207)
	at org.usfirst.ftc.server.Server.main(Server.java:246)
java.sql.SQLException: out of memory
	at org.sqlite.DB.throwex(DB.java:370)
	at org.sqlite.NestedDB._open(NestedDB.java:74)
	at org.sqlite.DB.open(DB.java:86)
	at org.sqlite.Conn.open(Conn.java:140)
	at org.sqlite.Conn.<init>(Conn.java:57)
	at org.sqlite.JDBC.createConnection(JDBC.java:77)
	at org.sqlite.JDBC.connect(JDBC.java:64)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at org.usfirst.ftc.event.SQLiteEventDAO.getConnection(SQLiteEventDAO.java:174)
	at org.usfirst.ftc.event.SQLiteEventDAO.getAllEvents(SQLiteEventDAO.java:199)
	at org.usfirst.ftc.event.EventsManager.init(EventsManager.java:73)
	at org.usfirst.ftc.server.Server.main(Server.java:247)
java.sql.SQLException: out of memory
	at org.sqlite.DB.throwex(DB.java:370)
	at org.sqlite.NestedDB._open(NestedDB.java:74)
	at org.sqlite.DB.open(DB.java:86)
	at org.sqlite.Conn.open(Conn.java:140)
	at org.sqlite.Conn.<init>(Conn.java:57)
	at org.sqlite.JDBC.createConnection(JDBC.java:77)
	at org.sqlite.JDBC.connect(JDBC.java:64)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at org.usfirst.ftc.event.SQLiteEventDAO.getConnection(SQLiteEventDAO.java:174)
	at org.usfirst.ftc.event.SQLiteEventDAO.getAllEvents(SQLiteEventDAO.java:188)
	at org.usfirst.ftc.event.EventsManager.init(EventsManager.java:73)
	at org.usfirst.ftc.server.Server.main(Server.java:247)
Exception in thread "main" java.lang.NullPointerException
	at org.usfirst.ftc.event.EventsManager.init(EventsManager.java:74)
	at org.usfirst.ftc.server.Server.main(Server.java:247)
```

**Comment by cmacfarl** [comment]
So we have tested the software on Macs.  You are getting an out of memory error.  What else do you have running on your machine?

Can you run top while launching the scorekeeping software and then report the results here?

**Comment by ofekashery** [comment]
I've run it now several times that all apps are closed, still not running, the same error

**Comment by adwiii** [comment]
Are you running it using the script at the top level?

**Comment by ofekashery** [comment]
Now it's working. I should have put it in the user folder. You didn't mention it anywhere

**Comment by adwiii** [comment]
I don't know what about putting it in the user folder would harm the system unless macOS is preventing read access from the directory for some reason. In any event, glad it is working.

**Comment by ofekashery** [comment]
It hasn't been fixed yet. The Scorekeeper doesn't start if it's not located in the home directory.
_(macOS Mojave 10.14, macOS Big Sur 11.2.3)_
