### ISSUE TITLE
Can not import league

### ISSUE THREAD

**Issue by khoyt5** [FIRST-Tech-Challenge/scorekeeper#407]
Experimenting with the latest Scorekeeper... I saved the league settings for an event I created. I then created a second event and tried to import the league and I get

NOT OK

The URL is http://localhost/event/evt2/dashboard/leagues/import/

This is the log:
	at java.lang.Thread.run(Unknown Source)
[qtp851898351-74] INFO org.usfirst.ftc.server.Server - Time: 10/09/2019 11:35:05:707 PM, Session: node01t5agdt4sqk2j1ctjvmn3ysg1r1, Route: http://localhost/event/evt2/dashboard/leagues/
[qtp851898351-65] INFO org.usfirst.ftc.server.Server - Time: 10/09/2019 11:35:22:929 PM, Session: node01t5agdt4sqk2j1ctjvmn3ysg1r1, Route: http://localhost/event/evt2/dashboard/leagues/import/
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(Unknown Source)
	at org.usfirst.ftc.event.league.LeagueRoutesLogic.lambda$static$4(LeagueRoutesLogic.java:86)
	at spark.RouteImpl$1.handle(RouteImpl.java:72)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1669)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:61)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.lang.Thread.run(Unknown Source)

**Comment by tvbarnette999** [comment]
What browser are you using?

**Comment by khoyt5** [comment]
Oops. I thought Chrome. My computer was just updated and I guess the default browser has been switched back to Edge. The database loads fine when using Chrome.

**Comment by adwiii** [comment]
As a followup, prior to v1.1.0, Edge would not work when importing Leagues/League Meets. This has been fixed in v1.1.0, although we still recommend using Chrome because of other limitations/limited testing with Edge.
