### ISSUE TITLE
Inspection page throws an HTTP 500 in a test (non-real) event

### ISSUE THREAD

**Issue by timtim17** [FIRST-Tech-Challenge/scorekeeper#692]
**Describe the bug**
Having an issue in an event I set up for testing, cannot repro in another event. Not sure what the root cause is or if this would happen in a real event.

When trying to open the field or robot inspection pages for any team in this particular event, the page shows an HTTP 500 error.

**To Reproduce**
1. Go to Robot/Field inspection and select a team to inspect (i.e. `/event/<key>/inspect/robot/<team>/`)
2. Observe "It appears that a Server error occurred. Please contact your FTA." Error 500.

**Expected behavior**
The robot/field inspection page loads.

**Screenshots**
<img width="1335" alt="image" src="https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/6354860/e1c0f632-7743-4d9d-9893-5c7f8a4765fa">

Logs:

```
15:59:27.547 [qtp1714243885-79] [] INFO  org.usfirst.ftc.server.Server - Time: 01/15/2024 03:59:27:546 PM, Session: Optional[06ed1977-77ab-43b5-bd10-5716c6f19413], User: local, Route: http://localhost/event/test/inspect/robot/417/ GET
15:59:27.548 [qtp1714243885-79] [] ERROR o.usfirst.ftc.utils.FTCDebugScreen - Page error
java.lang.NullPointerException: Cannot read the array length because "<parameter1>" is null
	at java.base/java.util.Arrays.stream(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ReduceOps$5.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.count(Unknown Source)
	at classpath//org.usfirst.ftc.event.inspection.InspectionSubsystem.join(InspectionSubsystem.java:206)
	at classpath//org.usfirst.ftc.event.inspection.InspectionSubsystem.getInspectionForm(InspectionSubsystem.java:219)
	at classpath//org.usfirst.ftc.event.inspection.InspectionRoutesLogic.lambda$static$13(InspectionRoutesLogic.java:373)
	at classpath//org.firstinspires.ftc.sparkshim.Route.handle(Route.java:23)
	at classpath//io.javalin.routing.HandlerEntry.handle(HandlerEntry.kt:19)
	at classpath//io.javalin.http.servlet.DefaultTasks.HTTP$lambda$8$lambda$6$lambda$5(DefaultTasks.kt:39)
	at classpath//io.javalin.http.servlet.JavalinServlet.handleTask(JavalinServlet.kt:88)
	at classpath//io.javalin.http.servlet.JavalinServlet.handleSync(JavalinServlet.kt:53)
	at classpath//io.javalin.http.servlet.JavalinServlet.service(JavalinServlet.kt:41)
	at classpath//jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at classpath//io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58)
	at classpath//jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at classpath//org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at classpath//org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
	at classpath//org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at classpath//org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
	at classpath//org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at classpath//org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
	at classpath//io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:61)
	at classpath//org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at classpath//org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at classpath//org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
	at classpath//org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at classpath//org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
	at classpath//org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at classpath//org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at classpath//org.eclipse.jetty.server.Server.handle(Server.java:563)
	at classpath//org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
	at classpath//org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
	at classpath//org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
	at classpath//org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
	at classpath//org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at classpath//org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at classpath//org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at classpath//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at classpath//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at classpath//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at classpath//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
	at classpath//org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at classpath//org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at classpath//org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at classpath//org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Unknown Source)
15:59:27.564 [qtp1714243885-79] [] INFO  org.eclipse.jetty.server.RequestLog - [localhost] [0:0:0:0:0:0:0:1] - - [15/Jan/2024:23:59:27 +0000] "GET /event/test/inspect/robot/417/ HTTP/1.1" 500 2926 "http://localhost/event/test/inspect/robot/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0" 21000
15:59:27.674 [qtp1714243885-63] [] INFO  org.usfirst.ftc.server.Server - Time: 01/15/2024 03:59:27:674 PM, Session: Optional[06ed1977-77ab-43b5-bd10-5716c6f19413], User: local, Route: http://localhost/releasenotes/ GET
15:59:27.675 [qtp1714243885-63] [] INFO  org.eclipse.jetty.server.RequestLog - [localhost] [0:0:0:0:0:0:0:1] - - [15/Jan/2024:23:59:27 +0000] "GET /releasenotes/ HTTP/1.1" 200 6373 "http://localhost/event/test/inspect/robot/417/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0" 1000
```

**Device (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] Edge
 - Version [e.g. 22] Edge 120.0.2210.133 (Official build) (arm64), macOS Sonoma 14.2.1, FTCLive v5.2.6

**Additional context**
Seems pretty low priority to me since it only happened in a test event, and not a real prod event. Not exactly sure what the root cause would be.

**Comment by timtim17** [comment]
For whatever reason, seems like my test event does not have any formRows in the DB, as opposed to another event that does.

<img width="1226" alt="image" src="https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/6354860/a361845b-a853-4d98-a1bb-250febd44618">

<img width="1226" alt="image" src="https://github.com/FIRST-Tech-Challenge/scorekeeper/assets/6354860/d7ee9ea3-1774-48ca-b089-2389994b6e06">

**Comment by maths22** [comment]
Could you upload a copy of the `db` and `data` directories from `~/Library/Application Support/org.firstinspires.ftclive-2024-default`

**Comment by timtim17** [comment]
[data.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/13954112/data.zip)
[db.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/13954113/db.zip)
[2024_01_16_10_01_04_AM.log](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/13954132/2024_01_16_10_01_04_AM.log)

**Comment by maths22** [comment]
Can you also attach a zip of the full logs directory (I meant to request that earlier but I forgot)?

**Comment by timtim17** [comment]
[org.firstinspires.ftclive-2024-default.zip](https://github.com/FIRST-Tech-Challenge/scorekeeper/files/13961070/org.firstinspires.ftclive-2024-default.zip)

**Comment by maths22** [comment]
Inspection forms are "frozen" at the time the event is setup, and it appears your original `test` event was created back on September 11, but we did not add inspection forms for CenterStage until ~10 days later, so that event would have ended up with empty inspection forms, and as you have discovered the scoring system doesn't really like empty inspection forms :)

Does this issue happen to you with a newly-created test event?  (From the logs it appears that you were not having this issue with your `test2` event, but if I am wrong please comment and reopen the issue.)

**Comment by timtim17** [comment]
Ahhh, that makes sense. Could perhaps be a bit more graceful of an error handle, but you are correct -- new events do work as expected. Thanks Jacob!

**Comment by maths22** [comment]
Yeah if we end up releasing a preview next season before inspection forms are ready again we'll try to make it not crash and burn quite so hard :)
