### ISSUE TITLE
Server 500 error trying to do an Inspection - and nothing is on the Inspection Status report

### ISSUE THREAD

**Issue by acharraggi** [FIRST-Tech-Challenge/scorekeeper#735]
**Describe the bug**
Server 500 errors trying to do inspections.

**To Reproduce**
Just running some tests. I tried to display the Inspection Status report but no teams were listed. 12 teams had been added.
Those team do show on the Inspectors list. I had separate Sizing from Hardware and could see the list of teams if I selected a Sizing inspection, but if I click a team number I get the 500 server error.

**Expected behavior**
Inspection status should not be blank and no 500 errors trying to inspect a team.

The inspection Status

**Screenshots**
![image](https://github.com/user-attachments/assets/a2342367-ef34-420f-bf77-3e3a54f6c8e2)

![image](https://github.com/user-attachments/assets/346d0e4a-f715-47ee-a8b9-7847a76b1c8c)

**Device (please complete the following information):**
 - OS: windows 10
 - Browser  chrome
 - Version current

**Additional context**

Here's the error in the log:
21:19:13.866 [JettyServerThreadPool-89] [] ERROR o.usfirst.ftc.utils.FTCDebugScreen - Page error
gg.jte.TemplateException: Failed to render event/inspect.jte
	at classpath//gg.jte.models.runtime.StaticJteModel.handleException(StaticJteModel.java:56)
	at classpath//gg.jte.models.runtime.StaticJteModel.render(StaticJteModel.java:38)
	at classpath//org.firstinspires.common.util.jte.JteRenderer$Extension.renderToString(JteRenderer.java:63)
	at classpath//org.firstinspires.common.util.jte.JteRenderer$Extension.render(JteRenderer.java:54)
	at classpath//org.usfirst.ftc.event.inspection.InspectionRoutesLogic.lambda$static$12(InspectionRoutesLogic.java:342)
	at classpath//io.javalin.router.Endpoint.handle(Endpoint.kt:52)
	at classpath//io.javalin.router.ParsedEndpoint.handle(ParsedEndpoint.kt:15)
	at classpath//io.javalin.http.servlet.DefaultTasks.HTTP$lambda$9$lambda$7$lambda$6(DefaultTasks.kt:52)
	at classpath//io.javalin.http.servlet.JavalinServlet.handleTask(JavalinServlet.kt:99)
	at classpath//io.javalin.http.servlet.JavalinServlet.handleSync(JavalinServlet.kt:64)
	at classpath//io.javalin.http.servlet.JavalinServlet.handle(JavalinServlet.kt:50)
	at classpath//io.javalin.http.servlet.JavalinServlet.service(JavalinServlet.kt:30)
	at classpath//jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at classpath//io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:52)
	at classpath//jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at classpath//org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at classpath//org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
	at classpath//org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at classpath//org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1580)
	at classpath//org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at classpath//org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
	at classpath//org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at classpath//org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at classpath//org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1553)
	at classpath//org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at classpath//org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
	at classpath//org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at classpath//org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at classpath//org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at classpath//org.eclipse.jetty.server.Server.handle(Server.java:563)
	at classpath//org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
	at classpath//org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
	at classpath//org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
	at classpath//org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
	at classpath//org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at classpath//org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at classpath//org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at classpath//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at classpath//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at classpath//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at classpath//org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
	at classpath//org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at classpath//org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at classpath//org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at classpath//org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot read the array length because "<parameter1>" is null
	at java.base/java.util.Arrays.stream(Unknown Source)
	at classpath//org.usfirst.ftc.jte.event.JteinspectGenerated$4.writeTo(JteinspectGenerated.java:150)
	at classpath//gg.jte.html.HtmlContent.writeTo(HtmlContent.java:12)
	at classpath//gg.jte.html.OwaspHtmlTemplateOutput.writeUserContent(OwaspHtmlTemplateOutput.java:52)
	at classpath//org.firstinspires.common.util.jte.JteHelper.preRenderContent(JteHelper.java:143)
	at classpath//org.usfirst.ftc.jte.JtelayoutGenerated$1.writeTo(JtelayoutGenerated.java:26)
	at classpath//gg.jte.html.HtmlContent.writeTo(HtmlContent.java:12)
	at classpath//gg.jte.html.OwaspHtmlTemplateOutput.writeUserContent(OwaspHtmlTemplateOutput.java:52)
	at classpath//org.firstinspires.common.util.jte.JteHelper.preRenderContent(JteHelper.java:143)
	at classpath//org.usfirst.ftc.jte.JtebaseLayoutGenerated.render(JtebaseLayoutGenerated.java:13)
	at classpath//org.usfirst.ftc.jte.JtelayoutGenerated.render(JtelayoutGenerated.java:17)
	at classpath//org.usfirst.ftc.jte.event.JteinspectGenerated.render(JteinspectGenerated.java:107)
	at classpath//org.usfirst.ftc.jte.StaticTemplates.lambda$eventInspect$33(StaticTemplates.java:527)
	at classpath//gg.jte.models.runtime.StaticJteModel.render(StaticJteModel.java:33)
	... 44 common frames omitted

**Comment by maths22** [comment]
Inspection is not supported in the first Into the Deep preview release.  We will mention in our release notes when inspection support has been added.
